version: "3.8"
services:
  app:
    build:
      args:
        user: gao
        uid: 1000
      context: .docker/php
    container_name: gao-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    labels: 
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:gao.localhost"

  db:
    image: mysql:5.7
    container_name: gao-db
    environment:
      - MYSQL_DATABASE=gao
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    ports: 
      - 8306:3306

  nginx:
    image: nginx:alpine
    container_name: gao-nginx
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d/

  # node:
  #   build:
  #     context: .docker/node
  #   container_name: gao-node
  #   volumes: 
  #     - .:/home/node/app/frontend

  traefik: 
    image: traefik:1.7
    container_name: gao-traefik
    command: --docker --docker.exposedbydefault=false
    ports: 
      - "80:80"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
